=== coderextreme/X3DJSONLD/src/specifications/X3dUnifiedObjectModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 rel. 3 (x64) (http://www.altova.com) by Don Brutzman (Naval Postgraduate School) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:appinfo>XML Schema for the Extensible 3D (X3D) Graphics Unified Object Model (X3DUOM) tagset</xs:appinfo>
		<xs:documentation><![CDATA[
=============================================================================

X3D Unified Object Model (X3DUOM) Schema
- identifier https://www.web3d.org/specifications/X3dUnifiedObjectModel.xsd
- reference  https://www.web3d.org/specifications/X3DUOM.html

Original Author:       Roy Walmsley
Co-Author, Maintainer: Don Brutzman

Acknowledgements:
- Grateful thanks to Don Brutzman for all his encouragement and insightful comments, without which
  this would never have materialized.

Design summary:
- This Schema details the design of the object model file, that is auto generated from the X3D schema
- An XSLT stylesheet can be applied to the object model to autogenerate source code for the Scene
  Authoring Interface (SAI), documentation of node lists, etc.

=============================================================================
		]]></xs:documentation>
	</xs:annotation>
	<xs:simpleType name="accessTypeValues">
		<xs:restriction base="xs:token">
			<xs:enumeration value="initializeOnly"/>
			<xs:enumeration value="inputOnly"/>
			<xs:enumeration value="inputOutput"/>
			<xs:enumeration value="outputOnly"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="fieldTypeValues">
		<xs:restriction base="xs:token">
			<xs:enumeration value="SFBool"/>
			<xs:enumeration value="SFColor"/>
			<xs:enumeration value="SFColorRGBA"/>
			<xs:enumeration value="SFDouble"/>
			<xs:enumeration value="SFFloat"/>
			<xs:enumeration value="SFImage"/>
			<xs:enumeration value="SFInt32"/>
			<xs:enumeration value="SFMatrix3d"/>
			<xs:enumeration value="SFMatrix3f"/>
			<xs:enumeration value="SFMatrix4d"/>
			<xs:enumeration value="SFMatrix4f"/>
			<xs:enumeration value="SFNode"/>
			<xs:enumeration value="SFRotation"/>
			<xs:enumeration value="SFString"/>
			<xs:enumeration value="SFTime"/>
			<xs:enumeration value="SFVec2d"/>
			<xs:enumeration value="SFVec2f"/>
			<xs:enumeration value="SFVec3d"/>
			<xs:enumeration value="SFVec3f"/>
			<xs:enumeration value="SFVec4d"/>
			<xs:enumeration value="SFVec4f"/>
			<xs:enumeration value="MFBool"/>
			<xs:enumeration value="MFColor"/>
			<xs:enumeration value="MFColorRGBA"/>
			<xs:enumeration value="MFDouble"/>
			<xs:enumeration value="MFFloat"/>
			<xs:enumeration value="MFImage"/>
			<xs:enumeration value="MFInt32"/>
			<xs:enumeration value="MFMatrix3d"/>
			<xs:enumeration value="MFMatrix3f"/>
			<xs:enumeration value="MFMatrix4d"/>
			<xs:enumeration value="MFMatrix4f"/>
			<xs:enumeration value="MFNode"/>
			<xs:enumeration value="MFRotation"/>
			<xs:enumeration value="MFString"/>
			<xs:enumeration value="MFTime"/>
			<xs:enumeration value="MFVec2d"/>
			<xs:enumeration value="MFVec2f"/>
			<xs:enumeration value="MFVec3d"/>
			<xs:enumeration value="MFVec3f"/>
			<xs:enumeration value="MFVec4d"/>
			<xs:enumeration value="MFVec4f"/>
			<xs:enumeration value="xs:string"/><!-- allowed for sourceCode CDATA blocks -->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="versionValues">
		<xs:restriction base="xs:string">
			<xs:enumeration value="3.0"/>
			<xs:enumeration value="3.1"/>
			<xs:enumeration value="3.2"/>
			<xs:enumeration value="3.3"/>
			<xs:enumeration value="4.0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="vrml97SupportValues">
		<xs:restriction base="xs:string">
			<xs:enumeration value="true"/>
			<xs:enumeration value="false"/>
			<xs:enumeration value="hasPrototypeSimple"/>
			<xs:enumeration value="hasPrototypeEcmaScript"/>
			<xs:enumeration value="hasPrototypeJava"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="AbstractNodeType">
		<xs:annotation>
			<xs:documentation>This element contains the definition for a single X3D abstract node type</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InterfaceDefinition"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:token" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="AbstractNodeTypes">
		<xs:annotation>
			<xs:documentation>This element contains all X3D abstract node types</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="AbstractNodeType"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="AbstractObjectType">
		<xs:annotation>
			<xs:documentation>This element contains the definition for single X3D abstract object types, meaning those that have no nodal constituents</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InterfaceDefinition"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:token" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="AbstractObjectTypes">
		<xs:annotation>
			<xs:documentation>This element contains all X3D abstract object types, meaning those that have no nodal constituents</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="AbstractObjectType"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="AdditionalInheritance">
		<xs:annotation>
			<xs:documentation>This element contains a secondary abstract type inherited by the abstract or concrete node type</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="baseType" type="xs:token" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="allowedElement"/>
	<xs:element name="componentInfo">
		<xs:annotation>
			<xs:documentation>This element contains the definition of the component info for a node or type</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" type="xs:token" default=""/>
			<xs:attribute name="level" default="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ConcreteNode">
		<xs:annotation>
			<xs:documentation>This element contains the definition for a single X3D concrete node type</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InterfaceDefinition"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:token" default=""/>
			<xs:attribute name="initialX3dVersion" type="versionValues" use="optional"/>
			<xs:attribute name="vrml97Support" type="vrml97SupportValues" use="optional" default="false"/>
			<!-- TODO required, not yet implemented in XML Schema -->
		</xs:complexType>
	</xs:element>
	<xs:element name="ConcreteNodes">
		<xs:annotation>
			<xs:documentation>This element contains all X3D concrete node types</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="ConcreteNode"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="containerField">
		<xs:annotation>
			<xs:documentation>This element contains the default value for the containerField attribute used in an XML encoding</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enumeration" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="default" type="xs:token" default=""/>
			<xs:attribute name="type" type="xs:token" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ContentModel">
		<xs:annotation>
			<xs:documentation>This element contains the definition for the child content model in a definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FieldDeclaration" minOccurs="0"/>
				<xs:element ref="GroupContentModel" minOccurs="0" maxOccurs="unbounded"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="NodeContentModel"/>
					<xs:element ref="StatementContentModel"/>
					<xs:element ref="SourceText" minOccurs="0"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="enumeration">
		<xs:annotation>
			<xs:documentation>This element contains a single value for an enumeration for a field</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="allowedElement" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="value" type="xs:string" default=""/>
			<xs:attribute name="appinfo" type="xs:string" default=""/>
			<xs:attribute name="documentation" type="xs:string" default=""/>
			<xs:attribute name="index" type="xs:string" default=""/>
			<xs:attribute name="alias" type="xs:string" default=""/>
			<xs:attribute name="loa" type="xs:string" default=""/>
			<xs:attribute name="parent" type="xs:string" default=""/>
			<xs:attribute name="description" type="xs:string" default=""/>
			<xs:attribute name="default" type="xs:string" default=""/><!-- default value -->
			<!-- xs:appinfo/xs:documentation/@source -->
			<!-- feature point attributes, typically empty and so xs:string here -->
		</xs:complexType>
	</xs:element>
	<xs:element name="field">
		<xs:annotation>
			<xs:documentation>This element contains the definition for a single built-in X3D field</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enumeration" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="componentInfo" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="acceptableNodeTypes" type="xs:string" default=""/>
			<xs:attribute name="accessType" type="accessTypeValues" default="inputOutput"/>
			<xs:attribute name="additionalEnumerationValuesAllowed" type="xs:boolean" default="false"/>
			<xs:attribute name="baseType" type="xs:token" default=""/>
			<xs:attribute name="componentLevel" type="xs:integer" default="1"/>
			<xs:attribute name="default" type="xs:string" default=""/>
			<xs:attribute name="description" type="xs:string" default=""/>
			<xs:attribute name="inheritedFrom" type="xs:token" default=""/>
			<xs:attribute name="initialX3dVersion" type="versionValues" use="optional"/>
			<xs:attribute name="maxExclusive" type="xs:token" default=""/>
			<xs:attribute name="maxInclusive" type="xs:token" default=""/>
			<xs:attribute name="minExclusive" type="xs:token" default=""/>
			<xs:attribute name="minInclusive" type="xs:token" default=""/>
			<xs:attribute name="name" type="xs:token" default=""/>
			<xs:attribute name="simpleType" type="xs:token" default=""/>
			<xs:attribute name="synonym" type="xs:token" default=""/>
			<xs:attribute name="type" type="fieldTypeValues" default="SFBool"/>
			<xs:attribute name="use" default="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="optional"/>
						<xs:enumeration value="required"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="FieldDeclaration">
		<xs:annotation>
			<xs:documentation>This element contains the specification user defined fields in the child content model in a definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="maxOccurs" type="xs:token" default="1"/>
			<xs:attribute name="minOccurs" type="xs:token" default="1"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FieldType">
		<xs:annotation>
			<xs:documentation>This element contains the definition for a single X3D field type</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InterfaceDefinition"/>
			</xs:sequence>
			<xs:attribute name="defaultValue" type="xs:string" default=""/>
			<xs:attribute name="isArray"   use="required"/><!-- value must be explicitly provided -->
			<xs:attribute name="tupleSize" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="16"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" type="xs:token" use="required"/>
			<xs:attribute name="regex" type="xs:string" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FieldTypes">
		<xs:annotation>
			<xs:documentation>This element contains all X3D field types</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="FieldType"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="GroupContentModel">
		<xs:annotation>
			<xs:documentation>This element contains the name of a group in the child content model in a definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="maxOccurs" type="xs:token" default="1"/>
			<xs:attribute name="minOccurs" type="xs:token" default="1"/>
			<xs:attribute name="name" type="xs:token" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Inheritance">
		<xs:annotation>
			<xs:documentation>This element contains the primary base abstract type inherited by the abstract or concrete node type</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="baseType" type="xs:token" default=""/>
			<xs:attribute name="x3dType" type="xs:token" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="InterfaceDefinition">
		<xs:annotation>
			<xs:documentation>This element contains an interface definition for an abstract object, abstract node, or concrete node</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="componentInfo" minOccurs="0"/>
				<xs:element ref="Inheritance" minOccurs="0"/>
				<xs:element ref="AdditionalInheritance" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="containerField" minOccurs="0"/>
				<xs:element ref="ContentModel" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="specificationSection" type="xs:string" default=""/>
			<xs:attribute name="specificationUrl" type="xs:string" default=""/>
			<xs:attribute name="appinfo" type="xs:string" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="NodeContentModel">
		<xs:annotation>
			<xs:documentation>This element contains the name of a particular node in the child content model in a definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="maxOccurs" type="xs:token" default="1"/>
			<xs:attribute name="minOccurs" type="xs:token" default="1"/>
			<xs:attribute name="name" type="xs:token" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SimpleType">
		<xs:annotation>
			<xs:documentation>This element defines a single SimpleType and its enumerations</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enumeration" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:token" default=""/>
			<xs:attribute name="baseType" type="xs:token" default=""/>
			<xs:attribute name="defaultValue" type="xs:string" default=""/>
			<xs:attribute name="regex" type="xs:string" default=""/>
			<xs:attribute name="appinfo" type="xs:string" default=""/>
			<xs:attribute name="documentation" type="xs:string" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SimpleTypeEnumerations">
		<xs:annotation>
			<xs:documentation>This element lists all simple types and their enumerations</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SimpleType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SourceText">
		<xs:annotation>
			<xs:documentation>This element indicates that the node may contain a plain text child, e.g. CDATA in XML or #sourceText in JSON</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Statement">
		<xs:annotation>
			<xs:documentation>This element contains the definition of a single statement</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InterfaceDefinition"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:token" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="StatementContentModel">
		<xs:annotation>
			<xs:documentation>This element contains the name of a particular statement in the child content model in a definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="maxOccurs" type="xs:token" default="1"/>
			<xs:attribute name="minOccurs" type="xs:token" default="1"/>
			<xs:attribute name="name" type="xs:token" default=""/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Statements">
		<xs:annotation>
			<xs:documentation>This element contains all X3D statements</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="Statement"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="X3dUnifiedObjectModel">
		<xs:annotation>
			<xs:documentation>Root element for the X3D Unified Object Model (X3DUOM) presented by this document.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SimpleTypeEnumerations" minOccurs="0"/>
				<xs:element ref="FieldTypes" minOccurs="0"/>
				<xs:element ref="AbstractObjectTypes" minOccurs="0"/>
				<xs:element ref="AbstractNodeTypes" minOccurs="0"/>
				<xs:element ref="ConcreteNodes" minOccurs="0"/>
				<xs:element ref="Statements" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="version" type="versionValues" default="3.3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== coderextreme/X3DJSONLD/src/main/lib/stylesheets/X3dUnifiedObjectModel-4.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- X3D Unified Object Model (X3DUOM) X3dUnifiedObjectModel-4.0.xml -->
<!-- Online at https://www.web3d.org/specifications/X3dUnifiedObjectModel-4.0.xml -->
<!-- This file contains a listing of all abstract and concrete nodes in version 4.0 of X3D -->
<!-- Generated 2021-09-15-05:00 19:59:09.553471792-05:00 -->
<X3dUnifiedObjectModel xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
                       version="4.0"
                       xsd:noNamespaceSchemaLocation="X3dUnifiedObjectModel.xsd">
   <SimpleTypeEnumerations>
      <!-- For schema xs:simpleType with contained xs:enumeration definitions, follow naming convention of name ending in 'Type', 'Choices' (for strict enumeration set) or 'Values' (for suggested tokens). -->
      <SimpleType name="accessTypeChoices"
                  baseType="xs:NMTOKEN"
                  appinfo="accessTypeChoices are strictly allowed enumeration values for accessType, used when defining field declarations within a Script node or ProtoDeclare/ExternProtoDeclare statements. Original accessType name values in VRML97 were eventIn, eventOut, field, exposedField respectively. Bounded, no additional values are allowed."
                  documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/concepts.html#FieldSemantics">
         <enumeration value="initializeOnly"
                      appinfo="A field with accessType initializeOnly can be initialized, but cannot send or receive events."/>
         <enumeration value="inputOnly"
                      appinfo="A field with accessType inputOnly cannot be initialized or included in a scene file, but can receive input event values via a ROUTE."/>
         <enumeration value="outputOnly"
                      appinfo="A field with accessType outputOnly cannot be initialized or included in a scene file, but can send output event values via a ROUTE."/>
         <enumeration value="inputOutput"
                      appinfo="A field with accessType inputOutput can be initialized, and can also send or receive events."/>
      </SimpleType>
      <SimpleType name="alphaModeChoices"
                  baseType="SFString"
                  appinfo="Permitted values for Appearance alphaMode field. Bounded, no additional values are allowed."
                  documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/Shape.html#Appearance">
         <enumeration value="AUTO"
                      appinfo="Material transparency is applied to texture transparency"/>
         <enumeration value="OPAQUE"
                      appinfo="Ignore alpha channel texture transparency, opaque"/>
         <enumeration value="MASK"
                      appinfo="Alpha-testing mode for transparent when alpha value less than 0.5 and opaque when greater than or equal to 0.5"/>
         <enumeration value="BLEND"
                      appinfo="Blend combines partial transparency of textures and materials"/>
      </SimpleType>
      <SimpleType name="appliedParametersChoices"
                  baseType="MFString"
                  appinfo="Default global parameters for collision outputs of rigid body physics system. Contact node can override parent CollisionCollection node. Multiple optional values, but appliedParameters enumerations cannot be extended. Bounded, no additional values are allowed."
                  documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/rigidBodyPhysics.html#t-AppliedParametersValidValues">
         <enumeration value="&#34;BOUNCE&#34;" appinfo="The bounce field value is used."/>
         <enumeration value="&#34;USER_FRICTION&#34;"
                      appinfo="The system will normally calculate the friction direction vector that is perpendicular to the contact normal. This setting indicates that the user-supplied value in this contact should be used."/>
         <enumeration value="&#34;FRICTION_COEFFICIENT-2&#34;"
                      appinfo="Apply frictionCoefficients values"/>
         <enumeration value="&#34;ERROR_REDUCTION&#34;" appinfo="Apply softnessErrorCorrection value"/>
         <enumeration value="&#34;CONSTANT_FORCE&#34;" appinfo="Apply softnessConstantForceMix value"/>
         <enumeration value="&#34;SPEED-1&#34;" appinfo="Apply first component of surfaceSpeed array"/>
         <enumeration value="&#34;SPEED-2&#34;"
                      appinfo="Apply second component of surfaceSpeed array"/>
         <enumeration value="&#34;SLIP-1&#34;" appinfo="Apply first component of slipFactors array"/>
         <enumeration value="&#34;SLIP-2&#34;" appinfo="Apply second component of slipFactors array"/>
      </SimpleType>
      <SimpleType name="bboxSizeType"
                  baseType="SFVec3f"
                  defaultValue="-1 -1 -1"
                  regex="\s*((([+]?(((0|[1-9][0-9]*)(\.[0-9]*)?|\.[0-9]+)([Ee][+-]?[0-9]+)?)\s+){2}([+]?((0|[1-9][0-9]*)(\.[0-9]*)?|\.[0-9]+)([Ee][+-]?[0-9]+)?)\s*)|((\-1(\.(0)*)?([Ee][+-]?[0]+)?\s+){2}\-1(\.(0)*)?([Ee][+-]?[0]+)?)\s*)?"
                  appinfo="bboxSizeType dimensions are non-negative values, default value (-1 -1 -1) indicates that no bounding box size has been computed."
                  documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/grouping.html#Boundingboxes"/>
      <SimpleType name="biquadTypeFilterChoices"
                  baseType="SFString"
                  appinfo="Permitted values for BiquadFilter type. Bounded, no additional values are allowed."
                  documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/sound.html#BiquadFilter">
         <enumeration value="lowpass"/>
         <enumeration value="highpass"/>
         <enumeration value="bandpass"/>
         <enumeration value="lowshelf"/>
         <enumeration value="highshelf"/>
         <enumeration value="peaking"/>
         <enumeration value="notch"/>
         <enumeration value="allpass"/>
      </SimpleType>
      <SimpleType name="channelCountModeChoices"
                  baseType="SFString"
                  appinfo="Permitted values for channelCountMode in X3DSoundChannelNode and X3DSoundDestinationNode. Bounded, no additional values are allowed."
                  documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/sound.html#SoundEffectsProcessing">
         <enumeration value="max"/>
         <enumeration value="clamped-max"/>
         <enumeration value="explicit"/>
      </SimpleType>
      <SimpleType name="channelInterpretationChoices"
                  baseType="SFString"
                  appinfo="Permitted values for channelInterpretation in X3DSoundChannelNode and X3DSoundDestinationNode. Bounded, no additional values are allowed."
                  documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/sound.html#SoundEffectsProcessing">
         <enumeration value="speakers"/>
         <enumeration value="discrete"/>
      </SimpleType>
      <SimpleType name="closureTypeChoices"
                  baseType="xs:NMTOKEN"
                  appinfo="closureTypeChoices are strictly allowed enumeration values for ArcClose2D closureType field. Bounded, no additional values are allowed."
                  documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/geometry2D.html#ArcClose2D">
         <enumeration value="PIE"
                      appinfo="Connects arc endpoints to center, forming a pie wedge"/>
         <enumeration value="CHORD"
                      appinfo="Connects arc endpoints directly to each other, as in chord on a circle"/>
      </SimpleType>
      <SimpleType name="componentNameChoices"
                  baseType="xs:NMTOKEN"
                  appinfo="componentNameChoices are enumeration constants used to identify the profile for each scene-graph node, and also utilized by X3D element to identify the components required by the contained Scene. Bounded, no additional values are allowed."
                  documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/concepts.html#Components">
         <enumeration value="Core"
                      appinfo="The Core component supplies the base functionality for the X3D run-time system, including the abstract base node type, field types, the event model, and routing."
                      documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/core.html"/>
         <enumeration value="CADGeometry"
                      appinfo="The CADGeometry component is provided for Computer-Aided Design (CAD) nodes."
                      documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/CADGeometry.html"/>
         <enumeration value="CubeMapTexturing"
                      appinfo="The Cube Map Environmental Texturing component describes how additional texturing effects are defined to produce environmental effects such as reflections from objects."
                      documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/environmentalTexturing"/>
         <enumeration value="DIS"
                      appinfo="The Distributed Interactive Simulation (DIS) component provides networked interoperability with the IEEE DIS protocol for sharing state and conducting real-time platform-level simulations across multiple host computers."
                      documentation="https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/dis.html"/>
         <enumeration value="EnvironmentalEffects"
